### ISSUE TITLE
controlling the device

### ISSUE THREAD

**Issue by cbeny** [mygnu/rcue#1]
This is great!  Are you aware of this project: https://github.com/jonasmalacofilho/liquidctl/issues/138 ?  That could help with your implementation of the control code. The "hydro platinum" driver seems quite similar: simply running it directly on my H150i (just adding the offset for the third fan) allowed me to get the correct fan/pump data, and to turn off the RGB as well.

**Comment by mygnu** [comment]
Thanks, I'll have look at this
